EnvironmentConfigurationMetadata:
  DateCreated: '1602345076000'
  DateModified: '1602345076000'
Platform:
  PlatformArn: arn:aws:elasticbeanstalk:eu-west-3::platform/Java 8 running on 64bit Amazon Linux/2.11.0
OptionSettings:
  aws:elasticbeanstalk:command:
    BatchSize: '30'
    Timeout: '1200'
    BatchSizeType: Percentage
    DeploymentPolicy: Immutable
  aws:elb:policies:
    ConnectionDrainingEnabled: true
  aws:elasticbeanstalk:application:environment:
    SPRING_PROFILES_ACTIVE: pro
  aws:elb:loadbalancer:
    CrossZone: true
  aws:elasticbeanstalk:environment:
    ServiceRole: arn:aws:iam::647020915193:role/aws-elasticbeanstalk-service-role
    LoadBalancerType: application
  aws:elasticbeanstalk:healthreporting:system:
    ConfigDocument:
      Version: 1
      CloudWatchMetrics:
        Instance:
          RootFilesystemUtil: null
          CPUIrq: null
          LoadAverage5min: null
          ApplicationRequests5xx: null
          ApplicationRequests4xx: null
          CPUUser: null
          LoadAverage1min: null
          ApplicationLatencyP50: null
          CPUIdle: null
          InstanceHealth: null
          ApplicationLatencyP95: null
          ApplicationLatencyP85: null
          ApplicationLatencyP90: null
          CPUSystem: null
          ApplicationLatencyP75: null
          CPUSoftirq: null
          ApplicationLatencyP10: null
          ApplicationLatencyP99: null
          ApplicationRequestsTotal: null
          ApplicationLatencyP99.9: null
          ApplicationRequests3xx: null
          ApplicationRequests2xx: null
          CPUIowait: null
          CPUNice: null
        Environment:
          InstancesSevere: null
          InstancesDegraded: null
          ApplicationRequests5xx: null
          ApplicationRequests4xx: null
          ApplicationLatencyP50: null
          ApplicationLatencyP95: null
          ApplicationLatencyP85: null
          InstancesUnknown: null
          ApplicationLatencyP90: null
          InstancesInfo: null
          InstancesPending: null
          ApplicationLatencyP75: null
          ApplicationLatencyP10: null
          ApplicationLatencyP99: null
          ApplicationRequestsTotal: null
          InstancesNoData: null
          ApplicationLatencyP99.9: null
          ApplicationRequests3xx: null
          ApplicationRequests2xx: null
          InstancesOk: null
          InstancesWarning: null
      Rules:
        Environment:
          ELB:
            ELBRequests4xx:
              Enabled: true
          Application:
            ApplicationRequests4xx:
              Enabled: true
    SystemType: enhanced
  AWSEBV2LoadBalancerTargetGroup.aws:elasticbeanstalk:environment:process:default:
    MatcherHTTPCode: '200'
    HealthCheckPath: /actuator/health
    Port: '8000'
  aws:autoscaling:launchconfiguration:
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
    EC2KeyName: aws-eb
  aws:rds:dbinstance:
    DBPassword: test123456
    DBEngine: postgres
    DBUser: postgres
  aws:autoscaling:updatepolicy:rollingupdate:
    RollingUpdateType: Health
    RollingUpdateEnabled: true
EnvironmentTier:
  Type: Standard
  Name: WebServer
Extensions:
  RDS.EBConsoleSnippet:
    Order: null
    SourceLocation: https://s3.eu-west-3.amazonaws.com/elasticbeanstalk-env-resources-eu-west-3/eb_snippets/rds/rds.json
AWSConfigurationTemplateVersion: 1.1.0.0
